import { z } from 'zod';

export const patientSchema = z.object({
  patient_id: z.number().optional(), // generated by backend
  mrn: z.string().optional(), // generated by backend
  title: z.string({ message: 'Title is required' }).min(1, 'Title is required'),
  firstName: z.string({ message: 'First name is required' }).min(1, 'First name is required'),
  lastName: z.string().optional(),
  dateOfBirth: z.string({ message: 'Date of Birth is required' }).min(1, 'Date of Birth is required'),
  age: z.number().optional(),
  gender: z.string({ message: 'Gender is required' }).min(1, 'Gender is required'),
  mobileNumber: z.string({ message: 'Mobile number is required' }).regex(/^\d{10}$/, 'Invalid mobile number'),
  address: z.string().optional().or(z.literal('')),
  area: z.string().optional().or(z.literal('')),
  city: z.string().optional().or(z.literal('')),
  state: z.string().optional().or(z.literal('')),
  country: z.string().optional().or(z.literal('')),
  pincode: z.string().optional().or(z.literal('')),
  aadhar: z.string().optional(),
  referalSource: z.string().optional(),
  comments: z.string().optional(),
});

export type PatientFormData = z.infer<typeof patientSchema>;
